---
# Configure Tomcat installation

- name: set tomcat user as owner and adm group as group for tomcat directories
  file:
       path="{{ item }}"
      owner=tomcat
      group=adm
    recurse=yes
  with_items:
    - /opt/data/tomcat8/conf
    - /opt/data//tomcat8/logs
    - /opt/data/tomcat8/temp
    - /opt/data/tomcat8/work
    - /opt/data/tomcat8/webapps

- name: set permissions for tomcat configuration files
  file:
    path="/opt/data/tomcat8/conf"
    mode=u+rw,g+rw
    recurse=yes
    state=directory

- name: ensure conventional locations exist for linking to tomcat directories
  file:
    path="{{ item }}"
    state=directory
  with_items:
    - /etc/tomcat8
    - /var/lib/tomcat8

- name: create symlinks to link conventional locations to tomcat directories
  file:
      src="{{ item.src }}"
     path="{{ item.path }}"
    state=link
  with_items:
 #   -
 #     src: /opt/tomcat8/conf
 #     path: /etc/tomcat8/conf
    -
      src: /opt/data/tomcat8/logs
      path: /var/log/tomcat8
    -
      src: /opt/data/tomcat8/webapps
      path: /var/lib/tomcat8/webapps

- name: Changing owner for Tomcat working directory
  command: find /opt/data/tomcat8/ -exec chown tomcat:tomcat {} \;
  #command: find /opt/data/tomcat8/ -type f -exec chown tomcat:tomcat {} \;

- name: generate systemd unit file for tomcat 8 - CentOS
  template:
     src=etc/systemd/system/tomcat8.service.j2
    dest=/etc/systemd/system/tomcat8.service
  notify:
    - Reload Systemd Daemon - CentOS
  when: ansible_distribution == "CentOS"

- name: ensure tomcat 8 service is started and enabled on start up - CentOS
  service:
       name=tomcat8
      state=started
    enabled=yes
  when: ansible_distribution == "CentOS"

- name: generate upstart script for tomcat 8 - Ubuntu
  template:
     src=etc/init/tomcat8.conf.j2
    dest=/etc/init/tomcat8.conf
  notify:
    - Reload Upstart Daemon - Ubuntu
    - Start Tomcat
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers
