---
# tasks file for ansible-centos7-nginx
- name: Add Nginx YUM repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Copy nginx_signing key
  copy: src=nginx_signing.key dest=/tmp/nginx_signing.key

- name: Import key
  rpm_key: state=present key=/tmp/nginx_signing.key

- name: Install latest nginx
  yum: name=nginx state=latest

- name: Copy template nginx, then restart
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes
  notify: reload nginx

- name: Ensure service is started and that it always starts on boot
  service: name=nginx state=started enabled=yes
