---
galaxy_info:
  author: Felix Fennell
  description: Downloads, installs and configures Apache Tomcat Java servlet container 8
  company: British Antarctic Survey

  issue_tracker_url: https://jira.ceh.ac.uk/browse/BARC
  license: MIT
  min_ansible_version: 1.8

  platforms:
  - name: EL
    versions:
      - 7
  - name: Ubuntu
    versions:
      - trusty

  galaxy_tags:
  - system

dependencies:
  - { role: 'oracle_java8',  tags: BARC_ROLE_DEPENDENCY }
