---
# Installs the Oracle JDK 7

- name: install prerequisites for downloading the oracle installer - CentOS
  yum:
                 pkg={{ item }}
        update_cache=yes
               state=present
  with_items:
    - wget

- name: determine if java is installed - CentOS
  command: java -version
  ignore_errors: true
  changed_when: false
  register: oracle_jdk7_fact_is_installed_centos

- name: download oracle jdk 7 installer - CentOS
  command: "wget -O /tmp/oracle-jdk7-installer.rpm --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.rpm'"
  args:
    creates: /tmp/oracle-jdk7-installer.rmp
  when: oracle_jdk7_fact_is_installed_centos.rc != 0

- name: install oracle jdk 7 - CentOS
  yum:
                 pkg={{ item }}
        update_cache=yes
               state=present
  with_items:
    - /tmp/oracle-jdk7-installer.rpm
  when: oracle_jdk7_fact_is_installed_centos.rc != 0

- name: cleanup oracle jdk 7 installer - CentOS
  file:
     path=/tmp/oracle-jdk7-installer.rpm
    state=absent
